name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x

    - name: Install Python Dependencies
      run: cd backend_flask_app && pip install -r requirements.txt
    
    - name: Run Flask Unit Tests
      run: cd backend_flask_app && python3 test_flaskr.py
  
  # deploy:

  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Set up AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v2
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1  # Remplacez par votre région AWS
    
  #   - name: Add SSH key
  #     uses: webfactory/ssh-agent@v0.5.3
  #     with:
  #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #   - name: Deploy to EC2
  #     run: |
  #       ssh -o StrictHostKeyChecking=no ubuntu@3.82.53.164 \
  #         "cd backend_flask_app && \
  #         if [ ! -d .git ]; then \
  #           git clone https://github.com/aristidedovi/removegb-kgtech.git .; \
  #         else \
  #           git pull origin main; \
  #         fi && \
  #         docker compose down && \
  #         docker compose up -d --build"